[package]
name = "app"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/greeting"]

[dependencies]
wit-bindgen = "0.38.0"
wit-bindgen-rt = { version = "0.38.0", features = ["bitflags"] }
